apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-server-deployment
    spec:
        replicas: 1
            selector:
                  matchLabels:
                          app: web-server
                              template:
                                    metadata:
                                            labels:
                                                      app: web-server
                                                            spec:
                                                                    containers:
                                                                            - name: web-server
                                                                                      image: ghanekar15/kubernetes-image:v5
                                                                                                ports:
                                                                                                          - containerPort: 80
